### ISSUE TITLE
Start

### ISSUE THREAD

**Issue by qeelex** [MikeTkachuk/Brawl-Stars-AI#1]
Hello,i d like to ask,how to start or train the ai on a IPhone or IPad,could you please say step by step how to move on and what to do.If it doesnt work for ios then describe please for me on Android bc i have 0 knowledge in programming and i wanna know how to make ai work.
Have a good day Sir

**Comment by MikeTkachuk** [comment]
Hello, I am almost completely sure that Apple devices do not support third party control of their devices, unless they are Jailbroken of course. I am currently working on a PC approach with BlueStacks. But the work is still in progress so not much to put into a step by step guide.
If you are curious about how ai may handle Brawl Stars here are some links:
https://spinningup.openai.com/en/latest/
https://github.com/danijar/dreamerv2
Regards
